const array = [
    {
        img: "../images/chart001.png",
        name: "ZZZ",
        presets: "Pattern",
        order: "Ticker",
        login: true,
        time: "1d",
        searched: "2 soat",
        id: 1,
        salarys: "+",
        symbol: 'BTCUSDT'
    },
    {
        img: "../images/Rasm.png",
        name: "ZYXI",
        presets: "Pattern",
        order: "Ticker",
        login: false,
        time: "1d",
        salarys: "+",
        id: 2,
        searched: "2 soat",
        symbol: 'ETHUSDT'
    },
    {
        img: "../images/chart001.png",
        name: "ZYME",
        presets: "Pattern",
        order: "Ticker",
        login: false,
        time: "1d",
        salarys: "-",
        id: 3,
        searched: "2 soat",
        symbol: 'BNBUSDT'
    },
    {
        img: "../images/chart001.png",
        name: "ZWS",
        presets: "Pattern",
        order: "Ticker",
        login: false,
        time: "1d",
        salarys: "-",
        id: 4,
        searched: "2 soat",
        symbol: 'XRPUSDT'
    },
    {
        img: "../images/chart001.png",
        name: "ZVSA",
        presets: "Pattern",
        order: "Ticker",
        login: false,
        time: "1d",
        salarys: "+",
        id: 5,
        searched: "2 soat",
        symbol: 'ADAUSDT'
    },
    {
        img: "../images/chart001.png",
        name: "ZVRA",
        presets: "Pattern",
        order: "Ticker",
        login: false,
        time: "1d",
        salarys: "+",
        id: 6,
        searched: "2 soat",
        symbol: 'DOGEUSDT'
    },
    {
        img: "../images/chart001.png",
        name: "ZURA",
        presets: "Pattern",
        order: "Ticker",
        login: false,
        time: "1d",
        salarys: "+",
        id: 7,
        searched: "2 soat",
        symbol: 'SOLUSDT'
    },
    {
        img: "../images/chart001.png",
        name: "ZUO",
        presets: "Pattern",
        order: "Ticker",
        login: false,
        time: "1d",
        salarys: "+",
        id: 8,
        searched: "2 soat"
    },
    {
        img: "../images/chart001.png",
        name: "ZUMZ",
        presets: "Pattern",
        order: "Tickers input filter",
        login: false,
        time: "1d",
        salarys: "+",
        id: 9,
        searched: "2 soat"
    },
    {
        img: "../images/chart001.png",
        name: "ZTWO",
        presets: "Pattern",
        order: "Tickers input filter",
        login: false,
        time: "1d",
        salarys: "+",
        id: 10,
        searched: "2 soat"
    },
    {
        img: "../images/chart001.png",
        name: "ZTS",
        presets: "Pattern",
        order: "Tickers input filter",
        login: false,
        time: "1d",
        salarys: "+",
        id: 11,
        searched: "2 soat"
    },
    {
        img: "../images/chart001.png",
        name: "ZTRE",
        presets: "Pattern",
        order: "Tickers input filter",
        login: false,
        salarys: "-",
        time: "1d",
        id: 12,
        searched: "2 soat"
    },
    {
        img: "../images/chart001.png",
        name: "ZTR",
        presets: "Pattern",
        order: "Price/Earnings",
        login: false,
        time: "1d",
        salarys: "-",
        id: 13,
        searched: "2 soat"
    },
    {
        img: "../images/chart001.png",
        name: "ZTO",
        presets: "Pattern",
        order: "Price/Earnings",
        login: false,
        time: "1d",
        salarys: "-",
        id: 14,
        searched: "2 soat"
    },
    {
        img: "../images/chart001.png",
        name: "ZTEN",
        presets: "Pattern",
        order: "Price/Earnings",
        login: false,
        time: "1d",
        salarys: "-",
        id: 15,
        searched: "2 soat"
    },
    {
        img: "../images/chart001.png",
        name: "ZTEK",
        presets: "Pattern",
        order: "Company",
        login: false,
        time: "1d",
        salarys: "-",
        id: 16,
        searched: "2 soat"
    },
    {
        img: "../images/chart001.png",
        name: "ZTAX",
        presets: "Pattern",
        order: "Company",
        login: false,
        time: "1d",
        salarys: "-",
        id: 17,
        searched: "2 soat"
    },
    {
        img: "../images/chart001.png",
        name: "ZSL",
        presets: "Pattern",
        order: "Company",
        login: false,
        time: "1d",
        salarys: "-",
        id: 18,
        searched: "2 soat"
    },
    {
        img: "../images/chart001.png",
        name: "ZSEP",
        presets: "Pattern",
        order: "Company",
        login: false,
        time: "1d",
        salarys: "-",
        id: 19,
        searched: "2 soat"
    },
    {
        img: "../images/chart001.png",
        name: "ZSC",
        presets: "Pattern",
        order: "Sector",
        login: false,
        time: "1d",
        salarys: "-",
        id: 20,
        searched: "2 soat"
    },
    {
        img: "../images/chart001.png",
        name: "ZSB",
        presets: "Pattern",
        order: "Sector",
        login: false,
        time: "1d",
        salarys: "-",
        id: 21,
        searched: "2 soat"
    },
    {
        img: "../images/chart001.png",
        name: "ZS",
        presets: "Pattern",
        order: "Sector",
        login: false,
        time: "1d",
        salarys: "-",
        id: 22,
        searched: "2 soat"
    },
    {
        img: "../images/chart001.png",
        name: "ZROZ",
        presets: "Pattern",
        order: "Industry",
        login: false,
        time: "1d",
        salarys: "-",
        id: 23,
        searched: "2 soat"
    },
    {
        img: "../images/chart001.png",
        name: "ZOOZ",
        presets: "Pattern",
        order: "Industry",
        login: false,
        time: "1d",
        salarys: "-",
        id: 24,
        searched: "2 soat"
    },
    {
        img: "../images/chart001.png",
        name: "ZONE",
        presets: "Pattern",
        order: "Industry",
        login: false,
        time: "1d",
        salarys: "-",
        id: 25,
        searched: "2 soat"
    },
    {
        img: "../images/chart001.png",
        name: "ZTO",
        presets: "Pattern",
        order: "Price/Earnings",
        login: false,
        time: "1d",
        salarys: "-",
        id: 26,
        searched: "2 soat"
    },
    {
        img: "../images/chart001.png",
        name: "ZTEN",
        presets: "Pattern",
        order: "Price/Earnings",
        login: false,
        time: "1d",
        salarys: "-",
        id: 27,
        searched: "2 soat"
    },
    {
        img: "../images/chart001.png",
        name: "ZTEK",
        presets: "Pattern",
        order: "Company",
        login: false,
        time: "1d",
        salarys: "-",
        id: 28,
        searched: "2 soat"
    },
    {
        img: "../images/chart001.png",
        name: "ZTAX",
        presets: "Pattern",
        order: "Company",
        login: false,
        time: "1d",
        salarys: "-",
        id: 29,
        searched: "2 soat"
    },
    {
        img: "../images/chart001.png",
        name: "ZSL",
        presets: "Pattern",
        order: "Company",
        login: false,
        time: "1d",
        salarys: "-",
        id: 30,
        searched: "2 soat"
    },
    {
        img: "../images/chart001.png",
        name: "ZSEP",
        presets: "Pattern",
        order: "Company",
        login: false,
        time: "1d",
        salarys: "-",
        id: 31,
        searched: "2 soat"
    },
    {
        img: "../images/chart001.png",
        name: "ZSC",
        presets: "Pattern",
        order: "Sector",
        login: false,
        time: "1d",
        salarys: "-",
        id: 32,
        searched: "2 soat"
    },
    {
        img: "../images/chart001.png",
        name: "ZSB",
        presets: "Pattern",
        order: "Sector",
        login: false,
        time: "1d",
        salarys: "-",
        id: 33,
        searched: "2 soat"
    },
    {
        img: "../images/chart001.png",
        name: "ZS",
        presets: "Pattern",
        order: "Sector",
        login: false,
        time: "1d",
        salarys: "-",
        id: 34,
        searched: "2 soat"
    },
    {
        img: "../images/chart001.png",
        name: "ZROZ",
        presets: "Pattern",
        order: "Industry",
        login: false,
        time: "1d",
        salarys: "-",
        id: 35,
        searched: "2 soat"
    },
    {
        img: "../images/chart001.png",
        name: "ZOOZ",
        presets: "Pattern",
        order: "Industry",
        login: false,
        time: "1d",
        salarys: "-",
        id: 36,
        searched: "2 soat"
    },
    {
        img: "../images/chart001.png",
        name: "ZONE",
        presets: "Pattern",
        order: "Industry",
        login: false,
        time: "1d",
        salarys: "-",
        id: 37,
        searched: "10 soat"
    },
]

export default array